/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from './apiError';

/**
 * Creates an instance of MessagingException
 */
 interface MessagingException {
  type: string;
  description: string;
}

export class MessagingExceptionError extends ApiError<MessagingException> {}

