/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from './apiError';

/**
 * Creates an instance of MessagingExceptionError
 */
interface MessagingExceptionError {
  type: string;
  description: string;
}

export class MessagingExceptionErrorError extends ApiError<MessagingExceptionError> {}
