/**
 * MessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');
/**
 * Creates an instance of GenericClientException
 */
class GenericClientException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.type = null;

        /**
         * TODO: Write general description for this field
         */
        this.description = null;

        /**
         * TODO: Write general description for this field
         */
        this.fieldErrors = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'type', realName: 'type' },
            { name: 'description', realName: 'description' },
            { name: 'fieldErrors', realName: 'fieldErrors', array: true, type: 'FieldError' },
        ]);
    }
}

module.exports = GenericClientException;
