/**
 * MessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');

/**
 * Creates an instance of PathClientException
 */
class PathClientException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.timestamp = null;

        /**
         * TODO: Write general description for this field
         */
        this.status = null;

        /**
         * TODO: Write general description for this field
         */
        this.error = null;

        /**
         * TODO: Write general description for this field
         */
        this.message = null;

        /**
         * TODO: Write general description for this field
         */
        this.path = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'timestamp', realName: 'timestamp' },
            { name: 'status', realName: 'status' },
            { name: 'error', realName: 'error' },
            { name: 'message', realName: 'message' },
            { name: 'path', realName: 'path' },
        ]);
    }
}

module.exports = PathClientException;
