/**
 * MessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of BandwidthCallbackMessage
 */
class BandwidthCallbackMessage extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.time = this.constructor.getValue(obj.time);
        this.type = this.constructor.getValue(obj.type);
        this.to = this.constructor.getValue(obj.to);
        this.errorCode = this.constructor.getValue(obj.errorCode);
        this.description = this.constructor.getValue(obj.description);
        this.message = this.constructor.getValue(obj.message);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'time', realName: 'time' },
            { name: 'type', realName: 'type' },
            { name: 'to', realName: 'to' },
            { name: 'errorCode', realName: 'errorCode' },
            { name: 'description', realName: 'description' },
            { name: 'message', realName: 'message', type: 'BandwidthMessage' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = BandwidthCallbackMessage;
