/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { HttpRequest } from './httpRequest';
import { HttpResponse } from './httpResponse';

/**
 * Context for an HTTP call
 */
export interface HttpContext {
  /** HTTP request */
  request: HttpRequest;
  /** HTTP response */
  response: HttpResponse;
}
