/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

/**
 * Interface for HTTP response data
 */
export interface HttpResponse {
  /** Response status code */
  statusCode: number;
  /** Original body from the response */
  body: string | Blob | NodeJS.ReadableStream;
  /** Response headers */
  headers: Record<string, string>;
}
