/**
 * MessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const servers = require('./Servers');
const environments = require('./Environments');
const apiHelper = require('./APIHelper');

const environmentsMap = [];

environmentsMap[environments.PRODUCTION] = [];
environmentsMap[environments.CUSTOM] = [];

environmentsMap[environments.PRODUCTION][servers.MDEFAULT] =
    'https://messaging.bandwidth.com/api/v2';
environmentsMap[environments.CUSTOM][servers.MDEFAULT] = '{base_url}';

const Configuration = {
    // The username to use with basic authentication
    // TODO: Replace the BasicAuthUserName with an appropriate value
    basicAuthUserName: 'TODO: Replace',

    // The password to use with basic authentication
    // TODO: Replace the BasicAuthPassword with an appropriate value
    basicAuthPassword: 'TODO: Replace',

    /**
     * base_url
     * @type {string}
     */
    baseUrl: 'https://www.example.com',

    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.PRODUCTION,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        const url = environmentsMap[this.currentEnvironment][server || servers.MDEFAULT];
        const urlParams = {
            baseUrl: { value: this.baseUrl, encode: false },
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
