/**
 * MessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Environments = {

    /**
     * TODO: Write general description for this element
     */
    PRODUCTION: 'production',

    /**
     * TODO: Write general description for this element
     */
    CUSTOM: 'custom',

};

module.exports = Environments;
