/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiResponse } from '../apiResponse';
import { MessagingExceptionError } from '../errors/messagingExceptionError';
import { FileWrapper } from '../fileWrapper';
import { RequestOptions } from '../http/requestBuilder';
import { Media, mediaSchema } from '../models/media';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';

export class MediaController extends BaseController {
  /**
   * listMedia
   *
   * @param accountId          User's account ID
   * @param continuationToken  Continuation token used to retrieve subsequent media.
   * @return Response from the API call
   */
  async listMedia(
    accountId: string,
    continuationToken?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Media[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      accountId: [accountId, string()],
      continuationToken: [continuationToken, optional(string())],
    });
    req.header('Continuation-Token', mapped.continuationToken);
    req.appendTemplatePath`/users/${mapped.accountId}/media`;
    req.throwOn(400, MessagingExceptionError, '400 Request is malformed or invalid');
    req.throwOn(401, MessagingExceptionError, '401 The specified user does not have access to the account');
    req.throwOn(403, MessagingExceptionError, '403 The user does not have access to this API');
    req.throwOn(404, MessagingExceptionError, '404 Path not found');
    req.throwOn(415, MessagingExceptionError, '415 The content-type of the request is incorrect');
    req.throwOn(429, MessagingExceptionError, '429 The rate limit has been reached');
    return req.callAsJson(array(mediaSchema), requestOptions);
  }

  /**
   * getMedia
   *
   * @param accountId User's account ID
   * @param mediaId   Media ID to retrieve
   * @return Response from the API call
   */
  async getMedia(
    accountId: string,
    mediaId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      accountId: [accountId, string()],
      mediaId: [mediaId, string()],
    });
    req.appendTemplatePath`/users/${mapped.accountId}/media/${mapped.mediaId}`;
    req.throwOn(400, MessagingExceptionError, '400 Request is malformed or invalid');
    req.throwOn(401, MessagingExceptionError, '401 The specified user does not have access to the account');
    req.throwOn(403, MessagingExceptionError, '403 The user does not have access to this API');
    req.throwOn(404, MessagingExceptionError, '404 Path not found');
    req.throwOn(415, MessagingExceptionError, '415 The content-type of the request is incorrect');
    req.throwOn(429, MessagingExceptionError, '429 The rate limit has been reached');
    return req.callAsStream(requestOptions);
  }

  /**
   * uploadMedia
   *
   * @param accountId     User's account ID
   * @param mediaId       The user supplied custom media ID
   * @param body
   * @param contentType   The media type of the entity-body
   * @param cacheControl  General-header field is used to specify directives that MUST be obeyed by all
   *                                     caching mechanisms along the request/response chain.
   * @return Response from the API call
   */
  async uploadMedia(
    accountId: string,
    mediaId: string,
    body: FileWrapper,
    contentType?: string,
    cacheControl?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      accountId: [accountId, string()],
      mediaId: [mediaId, string()],
      contentType: [contentType, optional(string())],
      cacheControl: [cacheControl, optional(string())],
    });
    req.header('Content-Type', mapped.contentType);
    req.header('Cache-Control', mapped.cacheControl);
    req.stream(body);
    req.appendTemplatePath`/users/${mapped.accountId}/media/${mapped.mediaId}`;
    req.throwOn(400, MessagingExceptionError, '400 Request is malformed or invalid');
    req.throwOn(401, MessagingExceptionError, '401 The specified user does not have access to the account');
    req.throwOn(403, MessagingExceptionError, '403 The user does not have access to this API');
    req.throwOn(404, MessagingExceptionError, '404 Path not found');
    req.throwOn(415, MessagingExceptionError, '415 The content-type of the request is incorrect');
    req.throwOn(429, MessagingExceptionError, '429 The rate limit has been reached');
    return req.call(requestOptions);
  }

  /**
   * deleteMedia
   *
   * @param accountId User's account ID
   * @param mediaId   The media ID to delete
   * @return Response from the API call
   */
  async deleteMedia(
    accountId: string,
    mediaId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      accountId: [accountId, string()],
      mediaId: [mediaId, string()],
    });
    req.appendTemplatePath`/users/${mapped.accountId}/media/${mapped.mediaId}`;
    req.throwOn(400, MessagingExceptionError, '400 Request is malformed or invalid');
    req.throwOn(401, MessagingExceptionError, '401 The specified user does not have access to the account');
    req.throwOn(403, MessagingExceptionError, '403 The user does not have access to this API');
    req.throwOn(404, MessagingExceptionError, '404 Path not found');
    req.throwOn(415, MessagingExceptionError, '415 The content-type of the request is incorrect');
    req.throwOn(429, MessagingExceptionError, '429 The rate limit has been reached');
    return req.call(requestOptions);
  }
}
