/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import { PriorityEnum, priorityEnumSchema } from './priorityEnum';

export interface MessageRequest {
  /** The ID of the Application your from number is associated with in the Bandwidth Phone Number Dashboard. */
  applicationId: string;
  /** The phone number(s) the message should be sent to in E164 format */
  to: string[];
  /** One of your telephone numbers the message should come from in E164 format */
  from: string;
  /** The contents of the text message. Must be 2048 characters or less. */
  text?: string;
  /** A list of URLs to include as media attachments as part of the message. */
  media?: string[];
  /** A custom string that will be included in callback events of the message. Max 1024 characters */
  tag?: string;
  /** The message's priority, currently for toll-free or short code SMS only. Messages with a priority value of `"high"` are given preference over your other traffic. */
  priority?: PriorityEnum;
}

export const messageRequestSchema: Schema<MessageRequest> = object({
  applicationId: ['applicationId', string()],
  to: ['to', array(string())],
  from: ['from', string()],
  text: ['text', optional(string())],
  media: ['media', optional(array(string()))],
  tag: ['tag', optional(string())],
  priority: ['priority', optional(priorityEnumSchema)],
});
