/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PriorityEnum
 */
export enum PriorityEnum {
  Default = 'default',
  High = 'high',
}

/**
 * Schema for PriorityEnum
 */
export const priorityEnumSchema: Schema<PriorityEnum> = stringEnum(PriorityEnum);
