/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import {
  BandwidthMessageItem,
  bandwidthMessageItemSchema,
} from './bandwidthMessageItem';
import { PageInfo, pageInfoSchema } from './pageInfo';

export interface BandwidthMessagesList {
  /** Total number of messages matched by the search */
  totalCount?: number;
  pageInfo?: PageInfo;
  messages?: BandwidthMessageItem[];
}

export const bandwidthMessagesListSchema: Schema<BandwidthMessagesList> = object(
  {
    totalCount: ['totalCount', optional(number())],
    pageInfo: ['pageInfo', optional(lazy(() => pageInfoSchema))],
    messages: [
      'messages',
      optional(array(lazy(() => bandwidthMessageItemSchema))),
    ],
  }
);
