/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema, unknown } from '../schema';

export interface DeferredResult {
  result?: unknown;
  setOrExpired?: boolean;
}

export const deferredResultSchema: Schema<DeferredResult> = object({
  result: ['result', optional(unknown())],
  setOrExpired: ['setOrExpired', optional(boolean())],
});
