/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Tag, tagSchema } from './tag';

export interface Media {
  inputStream?: unknown;
  content?: string;
  url?: string;
  contentLength?: string;
  contentType?: string;
  tags?: Tag[];
  /** User's account ID */
  userId?: string;
  mediaName?: string;
  mediaId?: string;
  cacheControl?: string;
}

export const mediaSchema: Schema<Media> = object({
  inputStream: ['inputStream', optional(unknown())],
  content: ['content', optional(string())],
  url: ['url', optional(string())],
  contentLength: ['contentLength', optional(string())],
  contentType: ['contentType', optional(string())],
  tags: ['tags', optional(array(lazy(() => tagSchema)))],
  userId: ['userId', optional(string())],
  mediaName: ['mediaName', optional(string())],
  mediaId: ['mediaId', optional(string())],
  cacheControl: ['cacheControl', optional(string())],
});
