/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Media {
  content?: string;
  contentLength?: number;
  mediaName?: string;
}

export const mediaSchema: Schema<Media> = object({
  content: ['content', optional(string())],
  contentLength: ['contentLength', optional(number())],
  mediaName: ['mediaName', optional(string())],
});
