/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PageInfo {
  /** The link to the previous page for pagination */
  prevPage?: string;
  /** The link to the next page for pagination */
  nextPage?: string;
  /** The isolated pagination token for the previous page */
  prevPageToken?: string;
  /** The isolated pagination token for the next page */
  nextPageToken?: string;
}

export const pageInfoSchema: Schema<PageInfo> = object({
  prevPage: ['prevPage', optional(string())],
  nextPage: ['nextPage', optional(string())],
  prevPageToken: ['prevPageToken', optional(string())],
  nextPageToken: ['nextPageToken', optional(string())],
});
