/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Tag {
  key?: string;
  value?: string;
}

export const tagSchema: Schema<Tag> = object({
  key: ['key', optional(string())],
  value: ['value', optional(string())],
});
