/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Configuration, Environment } from './configuration';

/** Default values for the configuration parameters of the client. */
export const DEFAULT_CONFIGURATION: Configuration = {
  timeout: 0,
  environment: Environment.Production,
  baseUrl: 'https://www.example.com',
  baseUrl: 'https://www.example.com',
  basicAuthUserName: 'TODO access token',
  basicAuthPassword: 'TODO access token',
};
