name: Deploy
on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Build and test npm package
      env:
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
        BW_NUMBER: ${{ secrets.BW_NUMBER }}
        USER_NUMBER: ${{ secrets.USER_NUMBER }}
      run: |
           npm install
           npm run build
           npm run test --if-present
    - name: Publish npm package
      run: |
            npm version $RELEASE_VERSION --no-git-tag-version
            npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
