name: Deploy
on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set Release Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Build and Test
      run: |
           npm install
           npm run build
           npm run test --if-present
    - name: Publish
      run: |
            npm version $RELEASE_VERSION
            npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
