name: Validate and Test

on:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Validate and Test 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install npm package
      run: npm install
    - name: Build npm package
      run: npm run build --if-present
    - name: Test npm package
      env:
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
        BW_NUMBER: ${{ secrets.BW_NUMBER }}
        USER_NUMBER: ${{ secrets.USER_NUMBER }}
      run: npm run test --if-present
    - uses: Bandwidth/build-notify-slack-action@v1.0.0
      if: failure()
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: ${{ secrets.SLACK_CHANNEL }}
