name: Validate SDK

on:
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    name: Validate SDK 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: NPM Install
      run: npm install
    - name: NPM Build
      run: npm run build --if-present
    - name: NPM Test
      run: npm run test --if-present
