name: Validate and Test

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    name: Validate and Test 
    runs-on: ubuntu-latest
    env:
      BANDWIDTH_ACCOUNT_ID: ${{ secrets.BANDWIDTH_ACCOUNT_ID }}
      BANDWIDTH_USERNAME: ${{ secrets.BANDWIDTH_USERNAME }}
      BANDWIDTH_PASSWORD: ${{ secrets.BANDWIDTH_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install npm package
      run: npm install
    - name: Build npm package
      run: npm run build --if-present
    - name: Test npm package
      run: npm run test --if-present
